//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurea.CRM.Client.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aurea.CRM.Client.UI.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Day.
        /// </summary>
        internal static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string basic_109 {
            get {
                return ResourceManager.GetString("basic_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not changed.
        /// </summary>
        internal static string basic_110 {
            get {
                return ResourceManager.GetString("basic_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string basic_111 {
            get {
                return ResourceManager.GetString("basic_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string basic_15 {
            get {
                return ResourceManager.GetString("basic_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string basic_16 {
            get {
                return ResourceManager.GetString("basic_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add this file to your Document Inbox, in order to upload it to a record..
        /// </summary>
        internal static string basic_171 {
            get {
                return ResourceManager.GetString("basic_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        internal static string basic_172 {
            get {
                return ResourceManager.GetString("basic_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file to Document Inbox.
        /// </summary>
        internal static string basic_173 {
            get {
                return ResourceManager.GetString("basic_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string basic_174 {
            get {
                return ResourceManager.GetString("basic_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string basic_22 {
            get {
                return ResourceManager.GetString("basic_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string basic_25 {
            get {
                return ResourceManager.GetString("basic_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Send Mail.
        /// </summary>
        internal static string basic_27 {
            get {
                return ResourceManager.GetString("basic_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must configure a Mail Account.
        /// </summary>
        internal static string basic_28 {
            get {
                return ResourceManager.GetString("basic_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string basic_36 {
            get {
                return ResourceManager.GetString("basic_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string basic_42 {
            get {
                return ResourceManager.GetString("basic_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Data Model &amp; Configuration.
        /// </summary>
        internal static string basic_7 {
            get {
                return ResourceManager.GetString("basic_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry All.
        /// </summary>
        internal static string basic_99 {
            get {
                return ResourceManager.GetString("basic_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarTitle {
            get {
                return ResourceManager.GetString("CalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Selected.
        /// </summary>
        internal static string client_ui_text_20 {
            get {
                return ResourceManager.GetString("client_ui_text_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        internal static string client_ui_text_21 {
            get {
                return ResourceManager.GetString("client_ui_text_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard All.
        /// </summary>
        internal static string client_ui_text_22 {
            get {
                return ResourceManager.GetString("client_ui_text_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection restored.
        /// </summary>
        internal static string ConnectionRestored {
            get {
                return ResourceManager.GetString("ConnectionRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string DetailViewMakePhoneCall {
            get {
                return ResourceManager.GetString("DetailViewMakePhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application registered to make a telephone call.
        /// </summary>
        internal static string DetailViewMPhoneCallNotSupported {
            get {
                return ResourceManager.GetString("DetailViewMPhoneCallNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be completed because it was rejected by the server..
        /// </summary>
        internal static string ErrorGeneralServerErrror {
            get {
                return ResourceManager.GetString("ErrorGeneralServerErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRMpad had a problem and crashed. Would you like to send a crash report to Aurea Software?.
        /// </summary>
        internal static string errors_16 {
            get {
                return ResourceManager.GetString("errors_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox not configured.
        /// </summary>
        internal static string errors_36 {
            get {
                return ResourceManager.GetString("errors_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can´t add this filetype to your Document Inbox.
        /// </summary>
        internal static string errors_37 {
            get {
                return ResourceManager.GetString("errors_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is too large for your document inbox..
        /// </summary>
        internal static string errors_38 {
            get {
                return ResourceManager.GetString("errors_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update for field(s) %@ denied due to access rights.
        /// </summary>
        internal static string errors_41 {
            get {
                return ResourceManager.GetString("errors_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM.Client window width &lt;320 pixels is not supported.
        /// </summary>
        internal static string errors_596 {
            get {
                return ResourceManager.GetString("errors_596", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM.Client window height &lt;500 pixels is not supported.
        /// </summary>
        internal static string errors_597 {
            get {
                return ResourceManager.GetString("errors_597", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum supported device resolution is iOS 320×568 points (1136x640 screen pixels), fewer resolutions are not supported in either dimension. 
        ///You can switch to another application, or close the application manually..
        /// </summary>
        internal static string errors_598 {
            get {
                return ResourceManager.GetString("errors_598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Errors.
        /// </summary>
        internal static string ErrorSynchronizationErrors {
            get {
                return ResourceManager.GetString("ErrorSynchronizationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server response (timeout).
        /// </summary>
        internal static string ErrorTimeout {
            get {
                return ResourceManager.GetString("ErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_1 {
            get {
                return ResourceManager.GetString("Login_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection available. Please check your internet connection..
        /// </summary>
        internal static string Login_10 {
            get {
                return ResourceManager.GetString("Login_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Login_1001 {
            get {
                return ResourceManager.GetString("Login_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome %@!.
        /// </summary>
        internal static string Login_1002 {
            get {
                return ResourceManager.GetString("Login_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your language.
        /// </summary>
        internal static string Login_1003 {
            get {
                return ResourceManager.GetString("Login_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply language.
        /// </summary>
        internal static string Login_1004 {
            get {
                return ResourceManager.GetString("Login_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Login rejected for this environment. Please Check your internet connection and login in online mode..
        /// </summary>
        internal static string Login_11 {
            get {
                return ResourceManager.GetString("Login_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more information.
        /// </summary>
        internal static string Login_1100 {
            get {
                return ResourceManager.GetString("Login_1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about Aurea CRM.
        /// </summary>
        internal static string Login_1101 {
            get {
                return ResourceManager.GetString("Login_1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for a Demo Account.
        /// </summary>
        internal static string Login_1102 {
            get {
                return ResourceManager.GetString("Login_1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview &amp; Tutorial.
        /// </summary>
        internal static string Login_1103 {
            get {
                return ResourceManager.GetString("Login_1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Aurea.
        /// </summary>
        internal static string Login_1104 {
            get {
                return ResourceManager.GetString("Login_1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update CRM on Twitter.
        /// </summary>
        internal static string Login_1105 {
            get {
                return ResourceManager.GetString("Login_1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update CRM on Facebook.
        /// </summary>
        internal static string Login_1106 {
            get {
                return ResourceManager.GetString("Login_1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Aurea.
        /// </summary>
        internal static string Login_1107 {
            get {
                return ResourceManager.GetString("Login_1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.aurea.com/contact-us.
        /// </summary>
        internal static string Login_1108 {
            get {
                return ResourceManager.GetString("Login_1108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aurea.com/about-aurea/vision.
        /// </summary>
        internal static string Login_1109 {
            get {
                return ResourceManager.GetString("Login_1109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aurea.com/products/crm.
        /// </summary>
        internal static string Login_1110 {
            get {
                return ResourceManager.GetString("Login_1110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.aurea.com/crmpad-demo.
        /// </summary>
        internal static string Login_1111 {
            get {
                return ResourceManager.GetString("Login_1111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://twitter.com/updateCRM.
        /// </summary>
        internal static string Login_1112 {
            get {
                return ResourceManager.GetString("Login_1112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/updateCRM.
        /// </summary>
        internal static string Login_1113 {
            get {
                return ResourceManager.GetString("Login_1113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password. Please check your login data and try again..
        /// </summary>
        internal static string Login_12 {
            get {
                return ResourceManager.GetString("Login_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Login.
        /// </summary>
        internal static string Login_1201 {
            get {
                return ResourceManager.GetString("Login_1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Logs.
        /// </summary>
        internal static string Login_1202 {
            get {
                return ResourceManager.GetString("Login_1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Login_1203 {
            get {
                return ResourceManager.GetString("Login_1203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Login_1204 {
            get {
                return ResourceManager.GetString("Login_1204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login_13 {
            get {
                return ResourceManager.GetString("Login_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        internal static string Login_1301 {
            get {
                return ResourceManager.GetString("Login_1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Sciences.
        /// </summary>
        internal static string Login_1302 {
            get {
                return ResourceManager.GetString("Login_1302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Services.
        /// </summary>
        internal static string Login_1303 {
            get {
                return ResourceManager.GetString("Login_1303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Goods.
        /// </summary>
        internal static string Login_1304 {
            get {
                return ResourceManager.GetString("Login_1304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login_1305 {
            get {
                return ResourceManager.GetString("Login_1305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login_1306 {
            get {
                return ResourceManager.GetString("Login_1306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login_1307 {
            get {
                return ResourceManager.GetString("Login_1307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login_1308 {
            get {
                return ResourceManager.GetString("Login_1308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general error occured. Please try again..
        /// </summary>
        internal static string Login_14 {
            get {
                return ResourceManager.GetString("Login_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection available.
        /// </summary>
        internal static string Login_15 {
            get {
                return ResourceManager.GetString("Login_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Login_16 {
            get {
                return ResourceManager.GetString("Login_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string Login_17 {
            get {
                return ResourceManager.GetString("Login_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon not possible.
        /// </summary>
        internal static string Login_18 {
            get {
                return ResourceManager.GetString("Login_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed.
        /// </summary>
        internal static string Login_19 {
            get {
                return ResourceManager.GetString("Login_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_2 {
            get {
                return ResourceManager.GetString("Login_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error  occurred during synchronization. Please try again..
        /// </summary>
        internal static string Login_20 {
            get {
                return ResourceManager.GetString("Login_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid update Mobile Services license for your account available. Please contact your administrator!.
        /// </summary>
        internal static string Login_21 {
            get {
                return ResourceManager.GetString("Login_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version.
        /// </summary>
        internal static string Login_22 {
            get {
                return ResourceManager.GetString("Login_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CRMpad version is no longer supported by the server..
        /// </summary>
        internal static string Login_23 {
            get {
                return ResourceManager.GetString("Login_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CRMpad version is no longer supported by the server. Please install the latest version..
        /// </summary>
        internal static string Login_24 {
            get {
                return ResourceManager.GetString("Login_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get latest version.
        /// </summary>
        internal static string Login_25 {
            get {
                return ResourceManager.GetString("Login_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Login_26 {
            get {
                return ResourceManager.GetString("Login_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Login_27 {
            get {
                return ResourceManager.GetString("Login_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string Login_28 {
            get {
                return ResourceManager.GetString("Login_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirmation do not match..
        /// </summary>
        internal static string Login_29 {
            get {
                return ResourceManager.GetString("Login_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Server selected.
        /// </summary>
        internal static string Login_3 {
            get {
                return ResourceManager.GetString("Login_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is expired and must be changed..
        /// </summary>
        internal static string Login_30 {
            get {
                return ResourceManager.GetString("Login_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server did not return any languages..
        /// </summary>
        internal static string Login_31 {
            get {
                return ResourceManager.GetString("Login_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Login_32 {
            get {
                return ResourceManager.GetString("Login_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization was cancelled.
        /// </summary>
        internal static string Login_33 {
            get {
                return ResourceManager.GetString("Login_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User is logged in with different Registration URL, close CRM.Client before registering another Registration URL.
        /// </summary>
        internal static string Login_34 {
            get {
                return ResourceManager.GetString("Login_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current server is already registered, please remove server registration before registering it again.
        /// </summary>
        internal static string Login_35 {
            get {
                return ResourceManager.GetString("Login_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current server url is already registered, please remove server registration before registering new server url.
        /// </summary>
        internal static string Login_36 {
            get {
                return ResourceManager.GetString("Login_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only default server is allowed.
        /// </summary>
        internal static string Login_37 {
            get {
                return ResourceManager.GetString("Login_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select default server from the list of servers.
        /// </summary>
        internal static string Login_38 {
            get {
                return ResourceManager.GetString("Login_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in progress....
        /// </summary>
        internal static string Login_4 {
            get {
                return ResourceManager.GetString("Login_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in progress....
        /// </summary>
        internal static string Login_5 {
            get {
                return ResourceManager.GetString("Login_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization in progress....
        /// </summary>
        internal static string Login_6 {
            get {
                return ResourceManager.GetString("Login_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password is incorrect..
        /// </summary>
        internal static string Login_7 {
            get {
                return ResourceManager.GetString("Login_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data has been synchronized for this user yet. Please check internet connection &amp; user name..
        /// </summary>
        internal static string Login_8 {
            get {
                return ResourceManager.GetString("Login_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The locally stored data is outdated. Please check your internet connection to perform a Full Sync..
        /// </summary>
        internal static string Login_9 {
            get {
                return ResourceManager.GetString("Login_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurea CRM.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meridiem.
        /// </summary>
        internal static string Meridiem {
            get {
                return ResourceManager.GetString("Meridiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available for this view.
        /// </summary>
        internal static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Events.
        /// </summary>
        internal static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send document.
        /// </summary>
        internal static string processes_19 {
            get {
                return ResourceManager.GetString("processes_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash.
        /// </summary>
        internal static string processes_5 {
            get {
                return ResourceManager.GetString("processes_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string processes_58 {
            get {
                return ResourceManager.GetString("processes_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetLogFile {
            get {
                return ResourceManager.GetString("ResetLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Log File.
        /// </summary>
        internal static string SendLogFile {
            get {
                return ResourceManager.GetString("SendLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        internal static string SettingsSyncFullViewModelSynchronizingText {
            get {
                return ResourceManager.GetString("SettingsSyncFullViewModelSynchronizingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurea CRM Client Version.
        /// </summary>
        internal static string SettingsSystemInfoApplicationVersionText {
            get {
                return ResourceManager.GetString("SettingsSystemInfoApplicationVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW LESS.
        /// </summary>
        internal static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW MORE.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported element.
        /// </summary>
        internal static string UnsupportedElementMessage {
            get {
                return ResourceManager.GetString("UnsupportedElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported view.
        /// </summary>
        internal static string UnsupportedViewMessage {
            get {
                return ResourceManager.GetString("UnsupportedViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workweek.
        /// </summary>
        internal static string Workweek {
            get {
                return ResourceManager.GetString("Workweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
